### ISSUE TITLE
Tiktoken dependency crashing Gem installation

### ISSUE THREAD

**Issue by prdanelli** [andreibondarev/langchainrb#470]
Firstly, thank you all so much for the time you have invested in this tool, its a massively appreciated tool. ❤️ 

Using the Docker Hub Ruby 3.2.2 Debian Bulleye container, the hard dependency of installing Tiktoken Ruby is causing `build` and gem installs to fail. 

Is there any other way to count tokens, rather than using Tiktoken Ruby, which seems to be looking for maintainers and hasn't yet been able to resolve issues around installing precompiled binaries?

The errors I'm seeing on install are: 

```
# bundle install inside of the docker container....

Fetching gem metadata from https://rubygems.org/.......
Installing tiktoken_ruby 0.0.7 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/bundle/gems/tiktoken_ruby-0.0.7/ext/tiktoken_ruby
/usr/local/bin/ruby extconf.rb
checking for gcc... yes
checking for g++... yes
checking for gcc-ar... yes
checking for cargo... no

current directory: /usr/local/bundle/gems/tiktoken_ruby-0.0.7/ext/tiktoken_ruby
make DESTDIR\= sitearchdir\=./.gem.20240215-1-simyyu sitelibdir\=./.gem.20240215-1-simyyu clean

current directory: /usr/local/bundle/gems/tiktoken_ruby-0.0.7/ext/tiktoken_ruby
make DESTDIR\= sitearchdir\=./.gem.20240215-1-simyyu sitelibdir\=./.gem.20240215-1-simyyu
info: downloading installer
Cannot execute /tmp/tmp.skww56pn8N/rustup-init (likely because of mounting /tmp as noexec).
Please copy the file to a location where you can execute binaries and run ./rustup-init.
make: *** [Makefile:550: /usr/local/bundle/gems/tiktoken_ruby-0.0.7/ext/tiktoken_ruby/.rb-sys/stable/cargo/bin/cargo] Error 1

make failed, exit code 2

Gem files will remain installed in /usr/local/bundle/gems/tiktoken_ruby-0.0.7 for inspection.
Results logged to /usr/local/bundle/extensions/aarch64-linux/3.2.0/tiktoken_ruby-0.0.7/gem_make.out

  /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:125:in `run'
  /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:51:in `block in make'
  /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:43:in `each'
  /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:43:in `make'
  /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/ext/ext_conf_builder.rb:42:in `build'
  /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:193:in `build_extension'
  /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:227:in `block in build_extensions'
  /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:224:in `each'
  /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:224:in `build_extensions'
  /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/installer.rb:852:in `build_extensions'
  /usr/local/bundle/gems/bundler-2.4.22/lib/bundler/rubygems_gem_installer.rb:76:in `build_extensions'
  /usr/local/bundle/gems/bundler-2.4.22/lib/bundler/rubygems_gem_installer.rb:28:in `install'
  /usr/local/bundle/gems/bundler-2.4.22/lib/bundler/source/rubygems.rb:203:in `install'
  /usr/local/bundle/gems/bundler-2.4.22/lib/bundler/installer/gem_installer.rb:54:in `install'
  /usr/local/bundle/gems/bundler-2.4.22/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /usr/local/bundle/gems/bundler-2.4.22/lib/bundler/installer/parallel_installer.rb:130:in `do_install'
  /usr/local/bundle/gems/bundler-2.4.22/lib/bundler/installer/parallel_installer.rb:121:in `block in worker_pool'
  /usr/local/bundle/gems/bundler-2.4.22/lib/bundler/worker.rb:62:in `apply_func'
  /usr/local/bundle/gems/bundler-2.4.22/lib/bundler/worker.rb:57:in `block in process_queue'
  /usr/local/bundle/gems/bundler-2.4.22/lib/bundler/worker.rb:54:in `loop'
  /usr/local/bundle/gems/bundler-2.4.22/lib/bundler/worker.rb:54:in `process_queue'
  /usr/local/bundle/gems/bundler-2.4.22/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'

An error occurred while installing tiktoken_ruby (0.0.7), and Bundler cannot continue.
```

Additionally, when trying to build a Ruby 3.2.2 container and install this Gem, i see the following: 

```
### ... 
99.73 Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
99.73
99.73 current directory:
99.73 /usr/local/bundle/gems/tiktoken_ruby-0.0.7/ext/tiktoken_ruby
99.73 /usr/local/bin/ruby extconf.rb
99.73 checking for gcc... yes
99.73 checking for g++... yes
99.73 checking for gcc-ar... yes
99.73 checking for cargo... no
99.73
99.73 current directory: /usr/local/bundle/gems/tiktoken_ruby-0.0.7/ext/tiktoken_ruby
99.73 make DESTDIR\= sitearchdir\=./.gem.20240215-28-riomdj
99.73 sitelibdir\=./.gem.20240215-28-riomdj clean
99.73
99.73 current directory: /usr/local/bundle/gems/tiktoken_ruby-0.0.7/ext/tiktoken_ruby
99.73 make DESTDIR\= sitearchdir\=./.gem.20240215-28-riomdj
99.73 sitelibdir\=./.gem.20240215-28-riomdj
99.73 info: downloading installer
99.73 info: profile set to 'minimal'
99.73 info: default host triple is aarch64-unknown-linux-gnu
99.73 info: skipping toolchain installation
99.73
99.73
99.73 Rust is installed now. Great!
99.73
99.73 To get started you need Cargo's bin directory
99.73 (/usr/local/bundle/gems/tiktoken_ruby-0.0.7/ext/tiktoken_ruby/.rb-sys/stable/cargo/bin)
99.73 in your PATH
99.73 environment variable. This has not been done automatically.
99.73
99.73 To configure your current shell, run:
99.73 source
99.73 "/usr/local/bundle/gems/tiktoken_ruby-0.0.7/ext/tiktoken_ruby/.rb-sys/stable/cargo/env"
99.73 info: syncing channel updates for 'stable-aarch64-unknown-linux-gnu'
99.73 info: latest update on 2024-02-08, rust version 1.76.0 (07dca489a 2024-02-04)
99.73 info: downloading component 'cargo'
99.73 info: downloading component 'rust-std'
99.73 info: downloading component 'rustc'
99.73 info: installing component 'cargo'
99.73 info: installing component 'rust-std'
99.73 info: installing component 'rustc'
99.73
99.73 stable-aarch64-unknown-linux-gnu installed - rustc 1.76.0 (07dca489a
99.73 2024-02-04)
99.73
99.73 info: default toolchain set to 'stable-aarch64-unknown-linux-gnu'
99.73 info: checking for self-update
99.73 info: using existing install for 'stable-aarch64-unknown-linux-gnu'
99.73 info: default toolchain set to 'stable-aarch64-unknown-linux-gnu'
99.73
99.73 stable-aarch64-unknown-linux-gnu unchanged - rustc 1.76.0 (07dca489a
99.73 2024-02-04)
99.73
99.73 info: note that the toolchain 'stable-aarch64-unknown-linux-gnu' is currently in
99.73 use (environment override by RUSTUP_TOOLCHAIN)
99.73 generating target/release/libtiktoken_ruby.so (release)
99.73 /usr/local/bundle/gems/tiktoken_ruby-0.0.7/ext/tiktoken_ruby/.rb-sys/stable/cargo/bin/cargo
99.73 rustc  --manifest-path ./Cargo.toml --target-dir target --lib --profile release
99.73 -- -C linker=gcc -L native=/usr/local/lib -C link-arg=-lm -l pthread
99.73     Updating crates.io index
99.73     Updating git repository `https://github.com/IAPark/tiktoken-rs.git`
99.73     Updating git submodule `https://github.com/zurawiki/tiktoken`
# ... 
99.73 Compiling tiktoken-rs v0.3.2
99.73 (https://github.com/IAPark/tiktoken-rs.git#5231fbf4)
99.73    Compiling magnus-macros v0.6.0
99.73    Compiling rb-sys-build v0.9.81
99.73    Compiling rb-sys v0.9.81
99.73 error: failed to run custom build command for `rb-sys v0.9.81`
99.73
99.73 Caused by:
99.73 process didn't exit successfully:
99.73 `/usr/local/bundle/gems/tiktoken_ruby-0.0.7/ext/tiktoken_ruby/target/release/build/rb-sys-cf5d654371f43146/build-script-main`
99.73 (exit status: 101)
99.73   --- stdout
99.73   cargo:rerun-if-env-changed=RUBY
99.73   cargo:rerun-if-env-changed=RBCONFIG_CROSS_COMPILING
99.73   cargo:rerun-if-env-changed=RBCONFIG_RUBY_PROGRAM_VERSION
99.73   cargo:rerun-if-env-changed=RBCONFIG_platform
99.73   cargo:rerun-if-env-changed=RUBY_ROOT
99.73   cargo:rerun-if-env-changed=RUBY_VERSION
99.73   cargo:rerun-if-env-changed=RUBY
99.73   cargo:rerun-if-changed=build/stable_api_config.rs
99.73   cargo:rerun-if-changed=build/main.rs
99.73   cargo:rerun-if-changed=build/features.rs
99.73   cargo:rerun-if-changed=build/version.rs
99.73   cargo:rerun-if-env-changed=RUBY_STATIC
99.73   cargo:rerun-if-env-changed=RBCONFIG_ENABLE_SHARED
99.73   cargo:rerun-if-env-changed=RBCONFIG_rubyhdrdir
99.73   cargo:rerun-if-env-changed=RBCONFIG_rubyarchhdrdir
99.73   cargo:rerun-if-env-changed=RBCONFIG_CPPFLAGS
99.73   cargo:rerun-if-env-changed=RBCONFIG_rubyhdrdir
99.73   cargo:rerun-if-env-changed=TARGET
99.73   cargo:rerun-if-env-changed=TARGET
99.73   cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_aarch64-unknown-linux-gnu
99.73   cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_aarch64-unknown-linux-gnu
99.73   cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_aarch64_unknown_linux_gnu
99.73   cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS_aarch64_unknown_linux_gnu
99.73   cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS
99.73   cargo:rerun-if-env-changed=BINDGEN_EXTRA_CLANG_ARGS
99.73
99.73   --- stderr
99.73 INFO: using bindgen with clang args: ["-I/usr/local/include/ruby-3.2.0",
99.73 "-I/usr/local/include/ruby-3.2.0/aarch64-linux", "-fms-extensions", "-O3",
99.73 "-fno-fast-math", "-ggdb3", "-Wall", "-Wextra", "-Wdeprecated-declarations",
99.73 "-Wdiv-by-zero", "-Wduplicated-cond", "-Wimplicit-function-declaration",
99.73 "-Wimplicit-int", "-Wmisleading-indentation", "-Wpointer-arith",
99.73 "-Wwrite-strings", "-Wold-style-definition", "-Wimplicit-fallthrough=0",
99.73 "-Wmissing-noreturn", "-Wno-cast-function-type",
99.73 "-Wno-constant-logical-operand", "-Wno-long-long",
99.73 "-Wno-missing-field-initializers", "-Wno-overlength-strings",
99.73 "-Wno-packed-bitfield-compat", "-Wno-parentheses-equality", "-Wno-self-assign",
99.73 "-Wno-tautological-compare", "-Wno-unused-parameter", "-Wno-unused-value",
99.73 "-Wsuggest-attribute=format", "-Wsuggest-attribute=noreturn",
99.73 "-Wunused-variable", "-Wundef"]
99.73 thread 'main' panicked at
99.73 /usr/local/bundle/gems/tiktoken_ruby-0.0.7/ext/tiktoken_ruby/.rb-sys/stable/cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.66.1/lib.rs:604:31:
99.73 Unable to find libclang: "couldn't find any valid shared libraries matching:
99.73 ['libclang.so', 'libclang-*.so', 'libclang.so.*', 'libclang-*.so.*'], set the
99.73 `LIBCLANG_PATH` environment variable to a path where one of these files can be
99.73 found (invalid: [])"
99.73   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
99.73 make: *** [Makefile:565: target/release/libtiktoken_ruby.so] Error 101
99.73
99.73 make failed, exit code 2
99.73
99.73 Gem files will remain installed in /usr/local/bundle/gems/tiktoken_ruby-0.0.7
99.73 for inspection.
99.73 Results logged to
99.73 /usr/local/bundle/extensions/aarch64-linux/3.2.0/tiktoken_ruby-0.0.7/gem_make.out
99.73
99.73   /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:125:in `run'
99.73 /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:51:in `block in
99.73 make'
99.73   /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:43:in `each'
99.73   /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:43:in `make'
99.73 /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/ext/ext_conf_builder.rb:42:in
99.73 `build'
99.73 /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:193:in
99.73 `build_extension'
99.73 /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:227:in `block in
99.73 build_extensions'
99.73   /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:224:in `each'
99.73 /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:224:in
99.73 `build_extensions'
99.73 /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/installer.rb:852:in
99.73 `build_extensions'
99.73 /usr/local/bundle/gems/bundler-2.4.22/lib/bundler/rubygems_gem_installer.rb:76:in
99.73 `build_extensions'
99.73 /usr/local/bundle/gems/bundler-2.4.22/lib/bundler/rubygems_gem_installer.rb:28:in
99.73 `install'
99.73 /usr/local/bundle/gems/bundler-2.4.22/lib/bundler/source/rubygems.rb:203:in
99.73 `install'
99.73 /usr/local/bundle/gems/bundler-2.4.22/lib/bundler/installer/gem_installer.rb:54:in
99.73 `install'
99.73 /usr/local/bundle/gems/bundler-2.4.22/lib/bundler/installer/gem_installer.rb:16:in
99.73 `install_from_spec'
99.73 /usr/local/bundle/gems/bundler-2.4.22/lib/bundler/installer/parallel_installer.rb:130:in
99.73 `do_install'
99.73 /usr/local/bundle/gems/bundler-2.4.22/lib/bundler/installer/parallel_installer.rb:121:in
99.73 `block in worker_pool'
99.73   /usr/local/bundle/gems/bundler-2.4.22/lib/bundler/worker.rb:62:in `apply_func'
99.73 /usr/local/bundle/gems/bundler-2.4.22/lib/bundler/worker.rb:57:in `block in
99.73 process_queue'
99.73   /usr/local/bundle/gems/bundler-2.4.22/lib/bundler/worker.rb:54:in `loop'
99.73 /usr/local/bundle/gems/bundler-2.4.22/lib/bundler/worker.rb:54:in
99.73 `process_queue'
99.73 /usr/local/bundle/gems/bundler-2.4.22/lib/bundler/worker.rb:90:in `block (2
99.73 levels) in create_threads'
99.73
99.73 An error occurred while installing tiktoken_ruby (0.0.7), and Bundler cannot
99.73 continue.
99.73
99.73 In Gemfile:
99.73   langchainrb was resolved to 0.9.2, which depends on
99.73     tiktoken_ruby

```

Any help would be hugely appreciated.

**Comment by andreibondarev** [comment]
@prdanelli Your `bundle install` as is? Feel free to share your Dockerfile so I can test it out locally.
