### ISSUE TITLE
Ruby 3.3 doesn't seem to be supported by pragmatic segmenter dependency

### ISSUE THREAD

**Issue by prdanelli** [andreibondarev/langchainrb#554]
Pragmatic Segmenter depends on Unicode, which doesn't seem to support Ruby 3.3. 

Bundle install error with Ruby 3.3
```
~/Dev/langchainrb main [!] v3.3.0
❯ bundle

Fetching gem metadata from https://rubygems.org/.........
Fetching Ascii85 1.1.0
Fetching multipart-post 2.4.0
Fetching drb 2.2.1
Fetching minitest 5.22.2
Fetching rack 3.0.9.1
Fetching afm 0.2.2
Fetching ai21 0.2.1
Fetching bigdecimal 3.1.6
Fetching aws-partitions 1.890.0
Installing Ascii85 1.1.0
Installing multipart-post 2.4.0
Fetching baran 0.1.10
Fetching zeitwerk 2.6.13
Installing drb 2.2.1
Fetching paco 0.2.3
Installing minitest 5.22.2
Fetching require-hooks 0.2.2
Installing rack 3.0.9.1
Fetching ruby-next-core 1.0.1
Installing afm 0.2.2
Fetching diff-lcs 1.5.1
Installing ai21 0.2.1
Fetching dotenv 2.7.6
Installing bigdecimal 3.1.6 with native extensions
Installing aws-partitions 1.890.0
Fetching io-console 0.7.2
Installing baran 0.1.10
Fetching dry-inflector 1.0.0
Installing zeitwerk 2.6.13
Fetching dry-initializer 3.1.1
Installing paco 0.2.3
Fetching polyglot 0.3.5
Installing require-hooks 0.2.2
Fetching google_search_results 2.0.1
Installing ruby-next-core 1.0.1
Installing diff-lcs 1.5.1
Installing dotenv 2.7.6
Fetching graphql 2.2.8
Fetching hashdiff 1.1.0
Fetching hashery 2.1.2
Installing io-console 0.7.2 with native extensions
Installing dry-inflector 1.0.0
Fetching hnswlib 0.8.1
Installing dry-initializer 3.1.1
Fetching unicode 0.4.4.4
Installing polyglot 0.3.5
Fetching tiktoken_ruby 0.0.7 (arm64-darwin)
Installing google_search_results 2.0.1
Fetching to_bool 2.0.0
Installing graphql 2.2.8
Installing hashdiff 1.1.0
Fetching lint_roller 1.1.0
Installing hashery 2.1.2
Fetching llama_cpp 0.9.5
Fetching parallel 1.24.0
Installing hnswlib 0.8.1 with native extensions
Installing unicode 0.4.4.4 with native extensions
Installing tiktoken_ruby 0.0.7 (arm64-darwin)
Installing to_bool 2.0.0
Fetching ruby-rc4 0.1.5
Installing lint_roller 1.1.0
Fetching pg 1.5.4
Fetching pgvector 0.2.2
Installing llama_cpp 0.9.5 with native extensions
Fetching rdiscount 2.2.7.3
Installing parallel 1.24.0
Fetching regexp_parser 2.9.0
Installing ruby-rc4 0.1.5
Fetching rspec-support 3.13.0
Installing pg 1.5.4 with native extensions
Installing pgvector 0.2.2
Fetching sequel 5.68.0
Installing rdiscount 2.2.7.3 with native extensions
Installing regexp_parser 2.9.0
Installing rspec-support 3.13.0
Fetching vcr 6.2.0
Fetching yard 0.9.36
Installing vcr 6.2.0
Installing sequel 5.68.0
Fetching nokogiri 1.16.2 (arm64-darwin)
Installing yard 0.9.36
Fetching addressable 2.8.6
Fetching net-http 0.4.1
Installing addressable 2.8.6
Installing nokogiri 1.16.2 (arm64-darwin)
Installing net-http 0.4.1
Fetching parser 3.3.0.5
Fetching safe_ruby 1.0.4
Fetching rack-session 2.0.0
Installing safe_ruby 1.0.4
Installing rack-session 2.0.0
Fetching rackup 2.1.0
Fetching dry-core 1.0.1
Installing parser 3.3.0.5
Installing rackup 2.1.0
Installing dry-core 1.0.1
Fetching elasticsearch-api 8.2.2
Fetching httparty 0.21.0
Installing elasticsearch-api 8.2.2
Installing httparty 0.21.0
Fetching treetop 1.6.12
Installing treetop 1.6.12
Fetching rspec-core 3.13.0
Installing rspec-core 3.13.0
Fetching rspec-expectations 3.13.0
Fetching rspec-mocks 3.13.0
Installing rspec-expectations 3.13.0
Installing rspec-mocks 3.13.0
Fetching reline 0.4.2
Installing reline 0.4.2
Fetching faraday-net_http 3.1.0
Fetching aws-sdk-core 3.191.1
Installing faraday-net_http 3.1.0
Fetching json-schema 4.0.0
Installing aws-sdk-core 3.191.1
Fetching wikipedia-client 1.17.0
Installing json-schema 4.0.0
Installing wikipedia-client 1.17.0
Fetching rdoc 6.6.3.1
Fetching dry-monads 1.6.0
Installing dry-monads 1.6.0
Installing rdoc 6.6.3.1
Fetching dry-configurable 1.1.0
Installing dry-configurable 1.1.0
Fetching dry-logic 1.5.0
Installing dry-logic 1.5.0
Fetching ruby-next-parser 3.2.2.0
Fetching unparser 0.6.13
Fetching net-imap 0.4.10
Installing ruby-next-parser 3.2.2.0
Installing unparser 0.6.13
Installing net-imap 0.4.10
Fetching net-smtp 0.4.0.1
Installing net-smtp 0.4.0.1
Fetching pry-byebug 3.10.1
Installing pry-byebug 3.10.1
Fetching eqn 1.6.5
Fetching rspec 3.13.0
Fetching faraday 2.9.0
Fetching docx 0.8.0
Fetching roo 2.10.1
Installing eqn 1.6.5
Fetching aws-sdk-bedrockruntime 1.5.0
Installing rspec 3.13.0
Fetching rubocop 1.60.2
Installing faraday 2.9.0
Installing docx 0.8.0
Fetching ruby-next 1.0.1
Fetching irb 1.11.2
Installing roo 2.10.1
Fetching anthropic 0.1.0
Installing aws-sdk-bedrockruntime 1.5.0
Fetching cohere-ruby 0.9.8
Installing rubocop 1.60.2
Installing ruby-next 1.0.1
Fetching elastic-transport 8.3.2
Installing irb 1.11.2
Fetching epsilla-ruby 0.0.4
Fetching faraday-retry 2.2.0
Installing anthropic 0.1.0
Fetching faraday-typhoeus 1.1.0
Fetching google-cloud-env 2.1.1
Fetching signet 0.19.0
Installing cohere-ruby 0.9.8
Fetching google_palm_api 0.1.3
Installing elastic-transport 8.3.2
Fetching hugging-face 0.3.5
Installing epsilla-ruby 0.0.4
Fetching milvus 0.9.2
Installing faraday-retry 2.2.0
Fetching qdrant-ruby 0.9.7
Installing faraday-typhoeus 1.1.0
Fetching ruby-openai 6.4.0
Installing google-cloud-env 2.1.1
Fetching chroma-db 0.6.0
Installing signet 0.19.0
Fetching rubocop-performance 1.20.2
Installing google_palm_api 0.1.3
Fetching standard-custom 1.0.2
Installing hugging-face 0.3.5
Fetching activesupport 7.1.3.2
Installing milvus 0.9.2
Fetching crack 0.4.6
Installing qdrant-ruby 0.9.7
Fetching dry-types 1.7.2
Installing ruby-openai 6.4.0
Fetching ttfunk 1.8.0
Installing chroma-db 0.6.0
Fetching elasticsearch 8.2.2
Installing rubocop-performance 1.20.2
Fetching replicate-ruby 0.2.3
Installing standard-custom 1.0.2
Fetching mistral-ai 1.2.0
Installing activesupport 7.1.3.2
Fetching googleauth 1.10.0
Installing crack 0.4.6
Fetching standard-performance 1.3.1
Installing dry-types 1.7.2
Fetching graphql-client 0.20.0
Installing ttfunk 1.8.0
Fetching open-weather-ruby-client 0.4.0
Fetching dry-schema 1.13.3
Installing elasticsearch 8.2.2
Fetching dry-struct 1.6.0
Installing replicate-ruby 0.2.3
Fetching actionview 7.1.3.2
Installing mistral-ai 1.2.0
Fetching pdf-reader 2.12.0
Installing googleauth 1.10.0
Fetching google-apis-core 0.13.0
Installing standard-performance 1.3.1
Fetching standard 1.34.0
Installing graphql-client 0.20.0
Fetching graphlient 0.7.0
Installing open-weather-ruby-client 0.4.0
Installing dry-schema 1.13.3
Fetching dry-validation 1.10.0
Installing dry-struct 1.6.0
Installing actionview 7.1.3.2
Fetching actionpack 7.1.3.2
Installing pdf-reader 2.12.0
Installing google-apis-core 0.13.0
Fetching google-apis-aiplatform_v1 0.13.0
Installing standard 1.34.0
Fetching standardrb 1.0.1
Installing graphlient 0.7.0
Fetching weaviate-ruby 0.8.10
Installing dry-validation 1.10.0
Fetching pinecone 0.1.71
Installing actionpack 7.1.3.2
Fetching railties 7.1.3.2
Installing google-apis-aiplatform_v1 0.13.0
Installing standardrb 1.0.1
Installing weaviate-ruby 0.8.10
Installing pinecone 0.1.71
Installing railties 7.1.3.2
Fetching dotenv-rails 2.7.6
Installing dotenv-rails 2.7.6

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/Users/paul/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/unicode-0.4.4.4/ext/unicode
/Users/paul/.asdf/installs/ruby/3.3.0/bin/ruby extconf.rb
creating Makefile

current directory:
/Users/paul/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/unicode-0.4.4.4/ext/unicode
make DESTDIR\= sitearchdir\=./.gem.20240403-85650-h21fab
sitelibdir\=./.gem.20240403-85650-h21fab clean

current directory:
/Users/paul/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/unicode-0.4.4.4/ext/unicode
make DESTDIR\= sitearchdir\=./.gem.20240403-85650-h21fab
sitelibdir\=./.gem.20240403-85650-h21fab
compiling unicode.c
unicode.c:37:7: warning: 'RB_OBJ_TAINTED' is deprecated: taintedness turned out to be a
wrong idea. [-Wdeprecated-declarations]
  if (OBJ_TAINTED(src))
      ^
/Users/paul/.asdf/installs/ruby/3.3.0/include/ruby-3.3.0/ruby/internal/fl_type.h:143:25:
note: expanded from macro 'OBJ_TAINTED'
#define OBJ_TAINTED     RB_OBJ_TAINTED     /**< @old{RB_OBJ_TAINTED} */
                        ^
/Users/paul/.asdf/installs/ruby/3.3.0/include/ruby-3.3.0/ruby/internal/fl_type.h:782:1:
note: 'RB_OBJ_TAINTED' has been explicitly marked deprecated here
RBIMPL_ATTR_DEPRECATED(("taintedness turned out to be a wrong idea."))
^
/Users/paul/.asdf/installs/ruby/3.3.0/include/ruby-3.3.0/ruby/internal/attr/deprecated.h:36:53:
note: expanded from macro 'RBIMPL_ATTR_DEPRECATED'
# define RBIMPL_ATTR_DEPRECATED(msg) __attribute__((__deprecated__ msg))
                                                    ^
unicode.c:38:5: warning: 'RB_OBJ_TAINT' is deprecated: taintedness turned out to be a
wrong idea. [-Wdeprecated-declarations]
    OBJ_TAINT(obj);
    ^
/Users/paul/.asdf/installs/ruby/3.3.0/include/ruby-3.3.0/ruby/internal/fl_type.h:141:25:
note: expanded from macro 'OBJ_TAINT'
#define OBJ_TAINT       RB_OBJ_TAINT       /**< @old{RB_OBJ_TAINT} */
                        ^
/Users/paul/.asdf/installs/ruby/3.3.0/include/ruby-3.3.0/ruby/internal/fl_type.h:815:1:
note: 'RB_OBJ_TAINT' has been explicitly marked deprecated here
RBIMPL_ATTR_DEPRECATED(("taintedness turned out to be a wrong idea."))
^
/Users/paul/.asdf/installs/ruby/3.3.0/include/ruby-3.3.0/ruby/internal/attr/deprecated.h:36:53:
note: expanded from macro 'RBIMPL_ATTR_DEPRECATED'
# define RBIMPL_ATTR_DEPRECATED(msg) __attribute__((__deprecated__ msg))
                                                    ^
unicode.c:646:50: warning: implicit conversion loses integer precision: 'long' to 'int'
[-Wshorten-64-to-32]
  WStr_allocWithUTF8L(&wstr1, RSTRING_PTR(str1), RSTRING_LEN(str1));
  ~~~~~~~~~~~~~~~~~~~                            ^~~~~~~~~~~~~~~~~
/Users/paul/.asdf/installs/ruby/3.3.0/include/ruby-3.3.0/ruby/internal/core/rstring.h:46:27:
note: expanded from macro 'RSTRING_LEN'
#define RSTRING_LEN       RSTRING_LEN
                          ^
unicode.c:647:50: warning: implicit conversion loses integer precision: 'long' to 'int'
[-Wshorten-64-to-32]
  WStr_allocWithUTF8L(&wstr2, RSTRING_PTR(str2), RSTRING_LEN(str2));
  ~~~~~~~~~~~~~~~~~~~                            ^~~~~~~~~~~~~~~~~
/Users/paul/.asdf/installs/ruby/3.3.0/include/ruby-3.3.0/ruby/internal/core/rstring.h:46:27:
note: expanded from macro 'RSTRING_LEN'
#define RSTRING_LEN       RSTRING_LEN
                          ^
unicode.c:688:50: warning: implicit conversion loses integer precision: 'long' to 'int'
[-Wshorten-64-to-32]
  WStr_allocWithUTF8L(&wstr1, RSTRING_PTR(str1), RSTRING_LEN(str1));
  ~~~~~~~~~~~~~~~~~~~                            ^~~~~~~~~~~~~~~~~
/Users/paul/.asdf/installs/ruby/3.3.0/include/ruby-3.3.0/ruby/internal/core/rstring.h:46:27:
note: expanded from macro 'RSTRING_LEN'
#define RSTRING_LEN       RSTRING_LEN
                          ^
unicode.c:689:50: warning: implicit conversion loses integer precision: 'long' to 'int'
[-Wshorten-64-to-32]
  WStr_allocWithUTF8L(&wstr2, RSTRING_PTR(str2), RSTRING_LEN(str2));
  ~~~~~~~~~~~~~~~~~~~                            ^~~~~~~~~~~~~~~~~
/Users/paul/.asdf/installs/ruby/3.3.0/include/ruby-3.3.0/ruby/internal/core/rstring.h:46:27:
note: expanded from macro 'RSTRING_LEN'
#define RSTRING_LEN       RSTRING_LEN
                          ^
unicode.c:725:48: warning: implicit conversion loses integer precision: 'long' to 'int'
[-Wshorten-64-to-32]
  WStr_allocWithUTF8L(&ustr, RSTRING_PTR(str), RSTRING_LEN(str));
  ~~~~~~~~~~~~~~~~~~~                          ^~~~~~~~~~~~~~~~
/Users/paul/.asdf/installs/ruby/3.3.0/include/ruby-3.3.0/ruby/internal/core/rstring.h:46:27:
note: expanded from macro 'RSTRING_LEN'
#define RSTRING_LEN       RSTRING_LEN
                          ^
unicode.c:751:48: warning: implicit conversion loses integer precision: 'long' to 'int'
[-Wshorten-64-to-32]
  WStr_allocWithUTF8L(&ustr, RSTRING_PTR(str), RSTRING_LEN(str));
  ~~~~~~~~~~~~~~~~~~~                          ^~~~~~~~~~~~~~~~
/Users/paul/.asdf/installs/ruby/3.3.0/include/ruby-3.3.0/ruby/internal/core/rstring.h:46:27:
note: expanded from macro 'RSTRING_LEN'
#define RSTRING_LEN       RSTRING_LEN
                          ^
unicode.c:777:48: warning: implicit conversion loses integer precision: 'long' to 'int'
[-Wshorten-64-to-32]
  WStr_allocWithUTF8L(&ustr, RSTRING_PTR(str), RSTRING_LEN(str));
  ~~~~~~~~~~~~~~~~~~~                          ^~~~~~~~~~~~~~~~
/Users/paul/.asdf/installs/ruby/3.3.0/include/ruby-3.3.0/ruby/internal/core/rstring.h:46:27:
note: expanded from macro 'RSTRING_LEN'
#define RSTRING_LEN       RSTRING_LEN
                          ^
unicode.c:803:48: warning: implicit conversion loses integer precision: 'long' to 'int'
[-Wshorten-64-to-32]
  WStr_allocWithUTF8L(&ustr, RSTRING_PTR(str), RSTRING_LEN(str));
  ~~~~~~~~~~~~~~~~~~~                          ^~~~~~~~~~~~~~~~
/Users/paul/.asdf/installs/ruby/3.3.0/include/ruby-3.3.0/ruby/internal/core/rstring.h:46:27:
note: expanded from macro 'RSTRING_LEN'
#define RSTRING_LEN       RSTRING_LEN
                          ^
unicode.c:830:49: warning: implicit conversion loses integer precision: 'long' to 'int'
[-Wshorten-64-to-32]
  WStr_allocWithUTF8L(&ustr1, RSTRING_PTR(str), RSTRING_LEN(str));
  ~~~~~~~~~~~~~~~~~~~                           ^~~~~~~~~~~~~~~~
/Users/paul/.asdf/installs/ruby/3.3.0/include/ruby-3.3.0/ruby/internal/core/rstring.h:46:27:
note: expanded from macro 'RSTRING_LEN'
#define RSTRING_LEN       RSTRING_LEN
                          ^
unicode.c:860:49: warning: implicit conversion loses integer precision: 'long' to 'int'
[-Wshorten-64-to-32]
  WStr_allocWithUTF8L(&ustr1, RSTRING_PTR(str), RSTRING_LEN(str));
  ~~~~~~~~~~~~~~~~~~~                           ^~~~~~~~~~~~~~~~
/Users/paul/.asdf/installs/ruby/3.3.0/include/ruby-3.3.0/ruby/internal/core/rstring.h:46:27:
note: expanded from macro 'RSTRING_LEN'
#define RSTRING_LEN       RSTRING_LEN
                          ^
unicode.c:890:49: warning: implicit conversion loses integer precision: 'long' to 'int'
[-Wshorten-64-to-32]
  WStr_allocWithUTF8L(&ustr1, RSTRING_PTR(str), RSTRING_LEN(str));
  ~~~~~~~~~~~~~~~~~~~                           ^~~~~~~~~~~~~~~~
/Users/paul/.asdf/installs/ruby/3.3.0/include/ruby-3.3.0/ruby/internal/core/rstring.h:46:27:
note: expanded from macro 'RSTRING_LEN'
#define RSTRING_LEN       RSTRING_LEN
                          ^
unicode.c:919:48: warning: implicit conversion loses integer precision: 'long' to 'int'
[-Wshorten-64-to-32]
  WStr_allocWithUTF8L(&ustr, RSTRING_PTR(str), RSTRING_LEN(str));
  ~~~~~~~~~~~~~~~~~~~                          ^~~~~~~~~~~~~~~~
/Users/paul/.asdf/installs/ruby/3.3.0/include/ruby-3.3.0/ruby/internal/core/rstring.h:46:27:
note: expanded from macro 'RSTRING_LEN'
#define RSTRING_LEN       RSTRING_LEN
                          ^
unicode.c:945:48: warning: implicit conversion loses integer precision: 'long' to 'int'
[-Wshorten-64-to-32]
  WStr_allocWithUTF8L(&ustr, RSTRING_PTR(str), RSTRING_LEN(str));
  ~~~~~~~~~~~~~~~~~~~                          ^~~~~~~~~~~~~~~~
/Users/paul/.asdf/installs/ruby/3.3.0/include/ruby-3.3.0/ruby/internal/core/rstring.h:46:27:
note: expanded from macro 'RSTRING_LEN'
#define RSTRING_LEN       RSTRING_LEN
                          ^
unicode.c:976:48: warning: implicit conversion loses integer precision: 'long' to 'int'
[-Wshorten-64-to-32]
  WStr_allocWithUTF8L(&ustr, RSTRING_PTR(str), RSTRING_LEN(str));
  ~~~~~~~~~~~~~~~~~~~                          ^~~~~~~~~~~~~~~~
/Users/paul/.asdf/installs/ruby/3.3.0/include/ruby-3.3.0/ruby/internal/core/rstring.h:46:27:
note: expanded from macro 'RSTRING_LEN'
#define RSTRING_LEN       RSTRING_LEN
                          ^
unicode.c:1039:20: error: incompatible function pointer types passing 'VALUE
(get_categories_param *)' (aka 'unsigned long (struct _get_categories_param *)') to
parameter of type 'VALUE (*)(VALUE)' (aka 'unsigned long (*)(unsigned long)')
[-Wincompatible-function-pointer-types]
  return rb_ensure(get_categories_internal, (VALUE)&param,
                   ^~~~~~~~~~~~~~~~~~~~~~~
/Users/paul/.asdf/installs/ruby/3.3.0/include/ruby-3.3.0/ruby/internal/iterator.h:425:25:
note: passing argument to parameter 'b_proc' here
VALUE rb_ensure(VALUE (*b_proc)(VALUE), VALUE data1, VALUE (*e_proc)(VALUE), VALUE
data2);
                        ^
unicode.c:1040:20: error: incompatible function pointer types passing 'VALUE (WString *)'
(aka 'unsigned long (struct _WString *)') to parameter of type 'VALUE (*)(VALUE)' (aka
'unsigned long (*)(unsigned long)') [-Wincompatible-function-pointer-types]
                   get_categories_ensure, (VALUE)&wstr);
                   ^~~~~~~~~~~~~~~~~~~~~
/Users/paul/.asdf/installs/ruby/3.3.0/include/ruby-3.3.0/ruby/internal/iterator.h:425:62:
note: passing argument to parameter 'e_proc' here
VALUE rb_ensure(VALUE (*b_proc)(VALUE), VALUE data1, VALUE (*e_proc)(VALUE), VALUE
data2);
                                                             ^
unicode.c:1037:48: warning: implicit conversion loses integer precision: 'long' to 'int'
[-Wshorten-64-to-32]
  WStr_allocWithUTF8L(&wstr, RSTRING_PTR(str), RSTRING_LEN(str));
  ~~~~~~~~~~~~~~~~~~~                          ^~~~~~~~~~~~~~~~
/Users/paul/.asdf/installs/ruby/3.3.0/include/ruby-3.3.0/ruby/internal/core/rstring.h:46:27:
note: expanded from macro 'RSTRING_LEN'
#define RSTRING_LEN       RSTRING_LEN
                          ^
unicode.c:1057:20: error: incompatible function pointer types passing 'VALUE
(get_categories_param *)' (aka 'unsigned long (struct _get_categories_param *)') to
parameter of type 'VALUE (*)(VALUE)' (aka 'unsigned long (*)(unsigned long)')
[-Wincompatible-function-pointer-types]
  return rb_ensure(get_categories_internal, (VALUE)&param,
                   ^~~~~~~~~~~~~~~~~~~~~~~
/Users/paul/.asdf/installs/ruby/3.3.0/include/ruby-3.3.0/ruby/internal/iterator.h:425:25:
note: passing argument to parameter 'b_proc' here
VALUE rb_ensure(VALUE (*b_proc)(VALUE), VALUE data1, VALUE (*e_proc)(VALUE), VALUE
data2);
                        ^
unicode.c:1058:20: error: incompatible function pointer types passing 'VALUE (WString *)'
(aka 'unsigned long (struct _WString *)') to parameter of type 'VALUE (*)(VALUE)' (aka
'unsigned long (*)(unsigned long)') [-Wincompatible-function-pointer-types]
                   get_categories_ensure, (VALUE)&wstr);
                   ^~~~~~~~~~~~~~~~~~~~~
/Users/paul/.asdf/installs/ruby/3.3.0/include/ruby-3.3.0/ruby/internal/iterator.h:425:62:
note: passing argument to parameter 'e_proc' here
VALUE rb_ensure(VALUE (*b_proc)(VALUE), VALUE data1, VALUE (*e_proc)(VALUE), VALUE
data2);
                                                             ^
unicode.c:1055:48: warning: implicit conversion loses integer precision: 'long' to 'int'
[-Wshorten-64-to-32]
  WStr_allocWithUTF8L(&wstr, RSTRING_PTR(str), RSTRING_LEN(str));
  ~~~~~~~~~~~~~~~~~~~                          ^~~~~~~~~~~~~~~~
/Users/paul/.asdf/installs/ruby/3.3.0/include/ruby-3.3.0/ruby/internal/core/rstring.h:46:27:
note: expanded from macro 'RSTRING_LEN'
#define RSTRING_LEN       RSTRING_LEN
                          ^
unicode.c:1079:48: warning: implicit conversion loses integer precision: 'long' to 'int'
[-Wshorten-64-to-32]
  WStr_allocWithUTF8L(&wstr, RSTRING_PTR(str), RSTRING_LEN(str));
  ~~~~~~~~~~~~~~~~~~~                          ^~~~~~~~~~~~~~~~
/Users/paul/.asdf/installs/ruby/3.3.0/include/ruby-3.3.0/ruby/internal/core/rstring.h:46:27:
note: expanded from macro 'RSTRING_LEN'
#define RSTRING_LEN       RSTRING_LEN
                          ^
unicode.c:1227:20: error: incompatible function pointer types passing 'VALUE
(get_text_elements_param *)' (aka 'unsigned long (struct _get_text_elements_param *)') to
parameter of type 'VALUE (*)(VALUE)' (aka 'unsigned long (*)(unsigned long)')
[-Wincompatible-function-pointer-types]
  return rb_ensure(get_text_elements_internal, (VALUE)&param,
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/paul/.asdf/installs/ruby/3.3.0/include/ruby-3.3.0/ruby/internal/iterator.h:425:25:
note: passing argument to parameter 'b_proc' here
VALUE rb_ensure(VALUE (*b_proc)(VALUE), VALUE data1, VALUE (*e_proc)(VALUE), VALUE
data2);
                        ^
unicode.c:1228:20: error: incompatible function pointer types passing 'VALUE (WString *)'
(aka 'unsigned long (struct _WString *)') to parameter of type 'VALUE (*)(VALUE)' (aka
'unsigned long (*)(unsigned long)') [-Wincompatible-function-pointer-types]
                   get_text_elements_ensure, (VALUE)&wstr);
                   ^~~~~~~~~~~~~~~~~~~~~~~~
/Users/paul/.asdf/installs/ruby/3.3.0/include/ruby-3.3.0/ruby/internal/iterator.h:425:62:
note: passing argument to parameter 'e_proc' here
VALUE rb_ensure(VALUE (*b_proc)(VALUE), VALUE data1, VALUE (*e_proc)(VALUE), VALUE
data2);
                                                             ^
unicode.c:1225:48: warning: implicit conversion loses integer precision: 'long' to 'int'
[-Wshorten-64-to-32]
  WStr_allocWithUTF8L(&wstr, RSTRING_PTR(str), RSTRING_LEN(str));
  ~~~~~~~~~~~~~~~~~~~                          ^~~~~~~~~~~~~~~~
/Users/paul/.asdf/installs/ruby/3.3.0/include/ruby-3.3.0/ruby/internal/core/rstring.h:46:27:
note: expanded from macro 'RSTRING_LEN'
#define RSTRING_LEN       RSTRING_LEN
                          ^
20 warnings and 6 errors generated.
make: *** [unicode.o] Error 1

make failed, exit code 2

Gem files will remain installed in
/Users/paul/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/unicode-0.4.4.4 for
inspection.
Results logged to
/Users/paul/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/extensions/arm64-darwin-23/3.3.0/unicode-0.4.4.4/gem_make.out

/Users/paul/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/rubygems/ext/builder.rb:125:in
`run'
/Users/paul/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/rubygems/ext/builder.rb:51:in
`block in make'
/Users/paul/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/rubygems/ext/builder.rb:43:in
`each'
/Users/paul/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/rubygems/ext/builder.rb:43:in
`make'
/Users/paul/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/rubygems/ext/ext_conf_builder.rb:42:in
`build'
/Users/paul/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/rubygems/ext/builder.rb:193:in
`build_extension'
/Users/paul/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/rubygems/ext/builder.rb:227:in
`block in build_extensions'
/Users/paul/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/rubygems/ext/builder.rb:224:in
`each'
/Users/paul/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/rubygems/ext/builder.rb:224:in
`build_extensions'
/Users/paul/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/rubygems/installer.rb:852:in
`build_extensions'
/Users/paul/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/bundler/rubygems_gem_installer.rb:76:in
`build_extensions'
/Users/paul/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/bundler/rubygems_gem_installer.rb:28:in
`install'
/Users/paul/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/bundler/source/rubygems.rb:205:in
`install'
/Users/paul/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/bundler/installer/gem_installer.rb:54:in
`install'
/Users/paul/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/Users/paul/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/bundler/installer/parallel_installer.rb:132:in
`do_install'
/Users/paul/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/bundler/installer/parallel_installer.rb:123:in
`block in worker_pool'
/Users/paul/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/bundler/worker.rb:62:in
`apply_func'
/Users/paul/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/bundler/worker.rb:57:in `block in
process_queue'
  <internal:kernel>:187:in `loop'
/Users/paul/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/bundler/worker.rb:54:in
`process_queue'
/Users/paul/.asdf/installs/ruby/3.3.0/lib/ruby/3.3.0/bundler/worker.rb:90:in `block (2
levels) in create_threads'

An error occurred while installing unicode (0.4.4.4), and Bundler cannot
continue.

In Gemfile:
  langchainrb was resolved to 0.10.3, which depends on
    pragmatic_segmenter was resolved to 0.3.23, which depends on
      unicode

```

When using Ruby 3.2.3

```❯ echo "ruby 3.2.3" > .tool-versions

~/Dev/langchainrb main [!] v3.2.3
❯ bundle
Fetching gem metadata from https://rubygems.org/.........
Fetching rack 3.0.9.1
Fetching yard 0.9.36
Fetching Ascii85 1.1.0
Fetching drb 2.2.1
Fetching ttfunk 1.8.0
Fetching rdoc 6.6.3.1
Fetching ruby-openai 6.4.0
Fetching ffi 1.16.3
Installing rack 3.0.9.1
Installing ruby-openai 6.4.0
Installing ttfunk 1.8.0
Installing yard 0.9.36
Installing rdoc 6.6.3.1
Installing drb 2.2.1
Fetching activesupport 7.1.3.2
Installing Ascii85 1.1.0
Installing ffi 1.16.3 with native extensions
Fetching pdf-reader 2.12.0
Installing activesupport 7.1.3.2
Installing pdf-reader 2.12.0
Fetching actionview 7.1.3.2
Installing actionview 7.1.3.2
Fetching actionpack 7.1.3.2
Installing actionpack 7.1.3.2
Fetching railties 7.1.3.2
Installing railties 7.1.3.2
Fetching ethon 0.16.0
Installing ethon 0.16.0
Fetching typhoeus 1.4.1
Installing typhoeus 1.4.1
Fetching faraday-typhoeus 1.1.0
Installing faraday-typhoeus 1.1.0
Fetching mistral-ai 1.2.0
Installing mistral-ai 1.2.0
Bundle complete! 44 Gemfile dependencies, 186 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

```

**Comment by andreibondarev** [comment]
@prdanelli Could you please give this a try: https://github.com/andreibondarev/langchainrb?tab=readme-ov-file#problems?

**Comment by prdanelli** [comment]
Arh, sorry @andreibondarev Didn't see the guide. I'll give it a try ASAP.

**Comment by andreibondarev** [comment]
@prdanelli No problem, I added it a week ago, tops.

**Comment by andreibondarev** [comment]
@prdanelli Did it fix your issue? If so -- please close this ticket.
