### ISSUE TITLE
Add additional examples to /examples

### ISSUE THREAD

**Issue by andreibondarev** [andreibondarev/langchainrb#74]
Add additional examples to /examples. We don't have all of the current functionality/use-cases documented. I think it's helpful to showcase what this library can and cannot do!

**Comment by mattlindsey** [comment]
Also need to fix the class names.  E.g.,
`weaviate = Vectorsearch::Weaviate.new(`
should be:
`weaviate = Langchain::Vectorsearch::Weaviate.new(`

And I'm getting a Gem::Conflict error:
```
➜  examples git:(main) ✗ ruby store_and_query_with_weaviate.rb
/Users/mattlindsey/.rvm/gems/ruby-3.2.1/gems/langchainrb-0.5.1/lib/langchain/dependency_helper.rb:31:in `rescue in depends_on': Could not load weaviate-ruby. Please ensure that the weaviate-ruby gem is installed. (LoadError)
	from /Users/mattlindsey/.rvm/gems/ruby-3.2.1/gems/langchainrb-0.5.1/lib/langchain/dependency_helper.rb:15:in `depends_on'
	from /Users/mattlindsey/.rvm/gems/ruby-3.2.1/gems/langchainrb-0.5.1/lib/langchain/vectorsearch/weaviate.rb:20:in `initialize'
	from store_and_query_with_weaviate.rb:7:in `new'
	from store_and_query_with_weaviate.rb:7:in `<main>'
/Users/mattlindsey/.rvm/rubies/ruby-3.2.1/lib/ruby/3.2.0/rubygems/specification.rb:2287:in `raise_if_conflicts': Unable to activate weaviate-ruby-0.8.2, because faraday-2.7.6 conflicts with faraday (~> 1) (Gem::ConflictError)
	from /Users/mattlindsey/.rvm/rubies/ruby-3.2.1/lib/ruby/3.2.0/rubygems/specification.rb:1418:in `activate'
	from /Users/mattlindsey/.rvm/rubies/ruby-3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_gem.rb:63:in `block in gem'
	from /Users/mattlindsey/.rvm/rubies/ruby-3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_gem.rb:63:in `synchronize'
	from /Users/mattlindsey/.rvm/rubies/ruby-3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_gem.rb:63:in `gem'
	from /Users/mattlindsey/.rvm/gems/ruby-3.2.1/gems/langchainrb-0.5.1/lib/langchain/dependency_helper.rb:16:in `depends_on'
	from /Users/mattlindsey/.rvm/gems/ruby-3.2.1/gems/langchainrb-0.5.1/lib/langchain/vectorsearch/weaviate.rb:20:in `initialize'
	from store_and_query_with_weaviate.rb:7:in `new'
	from store_and_query_with_weaviate.rb:7:in `<main>'

**Comment by andreibondarev** [comment]
@mattlindsey Good find -- I've fixed it here: https://github.com/andreibondarev/langchainrb/pull/146

**Comment by mattlindsey** [comment]
@andreibondarev Sorry if this is kind of minor, but the example file runs perfectly if I add a `require "weaviate"` at the top (see below), so it seems like something weird is going on.  I was surprised the Gemfile.lock for the project says we are using faraday 1.0 rather than something newer.

```ruby
require "langchain"
require "weaviate"

**Comment by andreibondarev** [comment]
I'm closing this for now. We can start a new issue in the future if needed.
