### ISSUE TITLE
Search tool requires an API key, raises error from serp_api library when missing

### ISSUE THREAD

**Issue by technicalpickles** [andreibondarev/langchainrb#99]
I was just trying out this simple chain of thought agent:

```ruby
agent = Langchain::Agent::ChainOfThoughtAgent.new(llm: :openai, llm_api_key: ENV["OPENAI_API_KEY"], tools: ['calculator'])
puts agent.run(question: "What is the square root of 99?")
```

It fails with:

```
server returns error for url: https://serpapi.com/search?q=%E2%88%9A99&engine=google&output=json&source=ruby
/Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/google_search_results-2.2.0/lib/search/serp_api_search.rb:143:in `rescue in get_results': Invalid API key. Your API key should be here: https://serpapi.com/manage-api-key (RuntimeError)
	from /Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/google_search_results-2.2.0/lib/search/serp_api_search.rb:136:in `get_results'
	from /Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/google_search_results-2.2.0/lib/search/serp_api_search.rb:50:in `get_json'
	from /Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/google_search_results-2.2.0/lib/search/serp_api_search.rb:64:in `get_hash'
	from /Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/langchainrb-0.4.1/lib/langchain/tool/serp_api.rb:50:in `execute_search'
	from /Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/langchainrb-0.4.1/lib/langchain/tool/serp_api.rb:27:in `execute_search'
	from /Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/langchainrb-0.4.1/lib/langchain/tool/calculator.rb:27:in `rescue in execute'
	from /Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/langchainrb-0.4.1/lib/langchain/tool/calculator.rb:20:in `execute'
	from /Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/langchainrb-0.4.1/lib/langchain/tool/base.rb:26:in `execute'
	from /Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/langchainrb-0.4.1/lib/langchain/agent/chain_of_thought_agent/chain_of_thought_agent.rb:66:in `block in run'
	from /Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/langchainrb-0.4.1/lib/langchain/agent/chain_of_thought_agent/chain_of_thought_agent.rb:44:in `loop'
	from /Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/langchainrb-0.4.1/lib/langchain/agent/chain_of_thought_agent/chain_of_thought_agent.rb:44:in `run'
	from main.rb:7:in `<main>'
/Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/3.2.0/open-uri.rb:369:in `open_http': 401 Unauthorized (OpenURI::HTTPError)
	from /Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/3.2.0/open-uri.rb:760:in `buffer_open'
	from /Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/3.2.0/open-uri.rb:214:in `block in open_loop'
	from /Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/3.2.0/open-uri.rb:212:in `catch'
	from /Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/3.2.0/open-uri.rb:212:in `open_loop'
	from /Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/3.2.0/open-uri.rb:153:in `open_uri'
	from /Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/3.2.0/open-uri.rb:740:in `open'
	from /Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/google_search_results-2.2.0/lib/search/serp_api_search.rb:139:in `get_results'
	from /Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/google_search_results-2.2.0/lib/search/serp_api_search.rb:50:in `get_json'
	from /Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/google_search_results-2.2.0/lib/search/serp_api_search.rb:64:in `get_hash'
	from /Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/langchainrb-0.4.1/lib/langchain/tool/serp_api.rb:50:in `execute_search'
	from /Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/langchainrb-0.4.1/lib/langchain/tool/serp_api.rb:27:in `execute_search'
	from /Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/langchainrb-0.4.1/lib/langchain/tool/calculator.rb:27:in `rescue in execute'
	from /Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/langchainrb-0.4.1/lib/langchain/tool/calculator.rb:20:in `execute'
	from /Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/langchainrb-0.4.1/lib/langchain/tool/base.rb:26:in `execute'
	from /Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/langchainrb-0.4.1/lib/langchain/agent/chain_of_thought_agent/chain_of_thought_agent.rb:66:in `block in run'
	from /Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/langchainrb-0.4.1/lib/langchain/agent/chain_of_thought_agent/chain_of_thought_agent.rb:44:in `loop'
	from /Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/langchainrb-0.4.1/lib/langchain/agent/chain_of_thought_agent/chain_of_thought_agent.rb:44:in `run'
	from main.rb:7:in `<main>'
/Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/eqn-1.6.5/lib/eqn/parser.rb:12:in `parse': Parse error at offset: 0 -- Expected one of "\s", "\t", 'if', 'IF', 'round', 'ROUND', 'roundup', 'ROUNDUP', 'rounddown', 'ROUNDDOWN', '(', '+', '-', [0-9], '.', [a-zA-Z] at line 1, column 1 (byte 1) (Eqn::ParseError)
	from /Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/eqn-1.6.5/lib/eqn/calculator.rb:66:in `calculate'
	from /Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/langchainrb-0.4.1/lib/langchain/tool/calculator.rb:23:in `execute'
	from /Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/langchainrb-0.4.1/lib/langchain/tool/base.rb:26:in `execute'
	from /Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/langchainrb-0.4.1/lib/langchain/agent/chain_of_thought_agent/chain_of_thought_agent.rb:66:in `block in run'
	from /Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/langchainrb-0.4.1/lib/langchain/agent/chain_of_thought_agent/chain_of_thought_agent.rb:44:in `loop'
	from /Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/langchainrb-0.4.1/lib/langchain/agent/chain_of_thought_agent/chain_of_thought_agent.rb:44:in `run'
	from main.rb:7:in `<main>'
```

I was kinda surprised that calculator uses the search tool. But I was also not expecting to give an API key.

I am imagining two pieces to this:

- update docs to make it clear to make an account
- check for SERP_API_KEY before using it, and give a nicer to read error, and refer to docs

**Comment by technicalpickles** [comment]
I am thinking to add something like `depends_on` but for environment variables (that thinking is what lead me to https://github.com/andreibondarev/langchainrb/pull/101). Maybe... `needs_env`, `requires_env`, or something in those veins.

By doing that, we can check the environment variable before trying to use it, and then have a human-readable error message with pointers to docs.

**Comment by andreibondarev** [comment]
@technicalpickles I haven't tried it but we might be able to use `dotenv` for this: https://github.com/bkeepers/dotenv#required-keys

**Comment by technicalpickles** [comment]
Oh wow, I've been a long time fan & user of dotenv, but didn't know it has that method 👀 👀 

It is really straightforward. The only concern I can think of so far is that it raises its own error (Dotenv::MissingKeys), so it'd be a question of exposing that to users directly, or rescue and raise our own.

**Comment by andreibondarev** [comment]
If we were to rescue and raise our own error and helpful message -- sounds like we'd need a custom method wrapping a call to `Dotenv.require_keys()`. I'm okay with it either way; obviously our own error + message would be a nicer UX.

**Comment by zewelor** [comment]
I like @technicalpickles idea about depends_on env / require_env etc. With custom method like that, we could also create something like "requested_envs['SOME_ENV']". It will be some wrapper that returnes only whitelisted/required envs for some class, for example to prevent accessing not declared envs somewhere later in a code. Ofc its not a protection against using ENV directly, but to faster see that I'm using something and I should have declared it explicit . Also we can keep some internal list which classes declared which envs they use, for example for auto generating documentions ? Like in this example ChainOfThoughtAgent needs this env to run etc.

**Comment by andreibondarev** [comment]
I'll work on this. I'll use a simple `Dotenv.require_keys()` for now.

**Comment by andreibondarev** [comment]
> I was kinda surprised that calculator uses the search tool.

@technicalpickles Yeah, it's a terrible hack, I added it to support these types of calculations:
<img width="899" alt="image" src="https://github.com/andreibondarev/langchainrb/assets/541665/d37d9ce9-3165-4200-8f47-b5cd812cf11a">

**Comment by andreibondarev** [comment]
@technicalpickles So I actually think that the SerpApi Tool should not be using the `ENV["SERP_API_KEY"]` directly rather the `api_key` should be set when the Tool is initialized, hence the following Issue: https://github.com/andreibondarev/langchainrb/issues/113

I'll close this issue for now.
